# Site settings
title: Ben Furfie
email: hello@benfurfie.co.uk
description: > #A blog about coding and the business of web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  # Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  # Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  # Author : ['Author', '/author/michelle', 'fa-user']
single_footer: '<p> &copy; 2015 Ben Furfie | <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Ben Furfie', '/about']


# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author_avatar: avatars/ben
      show_related_posts: true
      show_avatar: true

prose:
  rooturl: '_posts'
  siteurl: 'http://hmfaysal.github.io/Notepad/'
  relativeLinks: 'http://hmfaysal.github.io/Notepad/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post-sidebar"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "author_name"
        field:
          element: "text"
          label: "Author"
          value: Ben Furfie
      - name: "author_url"
        field:
          element: "text"
          label: "Author"
          value: /author/ben
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "wordpress"
              value: WordPress
            - name: "cmss"
              value: CMSs
            - name: "business-of-web-development"
              value: Business of Web Development
            # - name: "Psychology"
            #   value: psychology
            # - name: "Interesting"
            #   value: interesting
            # - name: "Web-Development"
            #   value: webdevelopment
          alterable: true
      - name: "feature_image"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "square_related"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
